# Configuration for Semantic Pull Requests
# https://github.com/zeke/semantic-pull-requests

# Validate PR title follows conventional commits
titleOnly: true

# Valid commit types
types:
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert

# Valid scopes
scopes:
  - scheduler
  - binder
  - podgrouper
  - admission
  - operator
  - queuecontroller
  - podgroupcontroller
  - resourcereservation
  - fairshare
  - chart
  - crd
  - api
  - nodescaleadjuster
  - scalingpod
  - deps
  - ci
  - release

# Scopes are optional
requireScope: false
