# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Pod
metadata:
  name: gpu-sharing-with-mps
  labels:
    runai/queue: test
  annotations:
    gpu-fraction: "0.5"
spec:
  schedulerName: kai-scheduler
  containers:
    - name: ubuntu
      image: ubuntu
      args: ["sleep", "infinity"]
      volumeMounts:
        - name: mps
          mountPath: /tmp/nvidia-mps
  volumes:
    - name: mps
      hostPath:
        path: /tmp/nvidia-mps
        type: DirectoryOrCreate