# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: jobset-example
  labels:
    kai.scheduler/queue: default-queue
spec:
  startupPolicy:
    startupPolicyOrder: AnyOrder
  successPolicy:
    operator: All
  failurePolicy:
    maxRestarts: 3
  replicatedJobs:
    - name: coordinator
      replicas: 1
      template:
        spec:
          parallelism: 1
          completions: 1
          backoffLimit: 0
          template:
            spec:
              schedulerName: kai-scheduler
              restartPolicy: OnFailure
              containers:
                - name: coordinator
                  image: busybox:1.36
                  command:
                    - /bin/sh
                    - -c
                    - |
                      echo "Coordinator starting"
                      sleep 10
                      echo "Coordinator completed"
                  resources:
                    requests:
                      cpu: "100m"
                      memory: "128Mi"
    - name: worker
      replicas: 2
      template:
        spec:
          parallelism: 2
          completions: 2
          backoffLimit: 0
          template:
            spec:
              schedulerName: kai-scheduler
              restartPolicy: OnFailure
              containers:
                - name: worker
                  image: busybox:1.36
                  command:
                    - /bin/sh
                    - -c
                    - |
                      echo "Worker starting: $HOSTNAME"
                      sleep 15
                      echo "Worker completed: $HOSTNAME"
                  resources:
                    requests:
                      cpu: "100m"
                      memory: "128Mi"
