# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resource.yaml

patches:
- path: mutating-webhook-patch.yaml
- path: validating-webhook-patch.yaml
- target:
    kind: MutatingWebhookConfiguration
    name: mutating-webhook-configuration
  patch: |-
    - op: replace
      path: /metadata/name
      value: kai-binder
- target:
    kind: ValidatingWebhookConfiguration
    name: validating-webhook-configuration
  patch: |-
    - op: replace
      path: /metadata/name
      value: kai-binder
