{{- if (lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "clusterversions.config.openshift.io") }}
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: kai-system
runAsUser:
  type: MustRunAs
  uid: 10000
seLinuxContext:
  type: MustRunAs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kai-system-scc
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - kai-system
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kai-system-scc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kai-system-scc
subjects:
  - kind: ServiceAccount
    name: admission
    namespace: kai-scheduler
  - kind: ServiceAccount
    name: binder
    namespace: kai-scheduler
  - kind: ServiceAccount
    name: kai-operator
    namespace: kai-scheduler
  - kind: ServiceAccount
    name: pod-grouper
    namespace: kai-scheduler
  - kind: ServiceAccount
    name: podgroup-controller
    namespace: kai-scheduler
  - kind: ServiceAccount
    name: queue-controller
    namespace: kai-scheduler
  - kind: ServiceAccount
    name: scheduler
    namespace: kai-scheduler
  - kind: ServiceAccount
    name: node-scale-adjuster
    namespace: kai-scheduler
  - kind: ServiceAccount
    name: kai-scheduler-crd-manager
    namespace: kai-scheduler
{{- end }}