# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kai-webhookmanager
  annotations:
    helm.sh/hook: pre-install,post-install,pre-upgrade,post-upgrade
    helm.sh/hook-weight: "-1"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
subjects:
  - kind: ServiceAccount
    name: webhookmanager
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: kai-webhookmanager
  apiGroup: rbac.authorization.k8s.io
