# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Pod
metadata:
  name: train-pod
  labels:
    kai.scheduler/queue: test
    priorityClassName: train
spec:
  schedulerName: kai-scheduler
  containers:
    - name: main
      image: ubuntu
      args: ["sleep", "infinity"]
      resources:
        limits:
          nvidia.com/gpu: "1"