# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Pod
metadata:
  name: pod-with-multiple-containers
spec:
  containers:
    - name: container-1
      image: k8s.gcr.io/pause:2.0
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
    - name: container-2
      image: k8s.gcr.io/pause:2.0
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"