# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
spec:
  parallelism: 2
  completions: 2
  template:
    metadata:
      labels:
        runai/queue: test
    spec:
      schedulerName: kai-scheduler
      restartPolicy: OnFailure
      containers:
        - name: main
          image: ubuntu
          args: ["sleep", "infinity"]
          resources:
            limits:
              nvidia.com/gpu: "1"