{
 "title": "Fair share VS usage",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "kai_queue_gpu_usage_devices", "legendFormat": "{{queue_name}} Usage" },
    {
     "expr": "sum_over_time(count(DCGM_FI_DEV_GPU_UTIL)[1h:1m])",
     "legendFormat": "Cluster Capacity"
    }
   ]
  },
  {
   "title": "Fair share",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "kai_queue_fair_share_gpu", "legendFormat": "{{queue_name}} Fair share" }
   ]
  },
  {
   "title": "Allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "kai_queue_allocated_gpus", "legendFormat": "{{queue_name}} Allocated" },
    { "expr": "count(DCGM_FI_DEV_GPU_UTIL)", "legendFormat": "Cluster Capacity" }
   ]
  }
 ]
}