# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

prometheus:
  enabled: true
grafana:
  enabled: true
  persistence:
    enabled: true
    type: pvc
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    # storageClassName: ""   # uncomment and set to your StorageClass if not using the default
    finalizers:
      - kubernetes.io/pvc-protection
  # Keep sidecars enabled so ConfigMaps like `docs/metrics/grafana-datasource.yaml`
  # (labeled with `grafana_datasource: "1"`) are automatically loaded.
  sidecar:
    datasources:
      enabled: true
    dashboards:
      enabled: true
