# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: binder
  namespace: kai-scheduler
  labels:
    accounting: kai-scheduler
spec:
  jobLabel: binder
  namespaceSelector:
    matchNames:
      - kai-scheduler
  selector:
    matchLabels:
      app: binder
  endpoints:
    - port: http-metrics
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scheduler
  namespace: kai-scheduler
  labels:
    accounting: kai-scheduler
spec:
  jobLabel: scheduler
  namespaceSelector:
    matchNames:
      - kai-scheduler
  selector:
    matchLabels:
      app: scheduler
  endpoints:
    - port: http-metrics
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: queuecontroller
  namespace: kai-scheduler
  labels:
    accounting: kai-scheduler
spec:
  jobLabel: queuecontroller
  namespaceSelector:
    matchNames:
      - kai-scheduler
  selector:
    matchLabels:
      app: queuecontroller
  endpoints:
    - port: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dcgm-exporter
  namespace: kai-scheduler
  labels:
    accounting: kai-scheduler
spec:
  jobLabel: dcgm-exporter
  namespaceSelector:
    matchNames:
      - gpu-operator
  selector:
    matchLabels:
      app: nvidia-dcgm-exporter
  endpoints:
    - port: gpu-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  namespace: kai-scheduler
  labels:
    accounting: kai-scheduler
spec:
  jobLabel: kube-state-metrics
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  endpoints:
    - port: http
      interval: 30s
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token