# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-binder
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: binder
      namespace: '{{ .Release.Namespace }}'
      path: /mutate--v1-pod
      port: 443
  failurePolicy: Fail
  name: binder.run.ai
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
      - '{{ .Release.Namespace }}'
  reinvocationPolicy: IfNeeded
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-binder
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: binder
      namespace: '{{ .Release.Namespace }}'
      path: /validate--v1-pod
      port: 443
  failurePolicy: Fail
  name: binder.run.ai
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
      - '{{ .Release.Namespace }}'
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: None
