# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kai-queuecontroller
  labels:
    app: queuecontroller
webhooks:
  - name: queues.scheduling.run.ai
    clientConfig:
      service:
        name: queuecontroller
        namespace: {{ .Release.Namespace }}
        path: /validate-scheduling-run-ai-v2-queue
        port: 443
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["scheduling.run.ai"]
        apiVersions: ["*"]
        resources: ["queues"]
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 5
