# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.global.clusterAutoscaling }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-scale-adjuster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-scale-adjuster
  template:
    metadata:
      labels:
        app: node-scale-adjuster
    spec:
      serviceAccountName: node-scale-adjuster
      containers:
        - name: node-scale-adjuster
          image: "{{ .Values.global.registry }}/{{ .Values.nodescaleadjuster.image.name }}:{{ .Chart.Version }}"
          imagePullPolicy: {{ .Values.podgrouper.image.pullPolicy }}
          args:
            - "--scaling-pod-image={{ .Values.global.registry }}/{{ .Values.nodescaleadjuster.scalingPodImage.name }}:{{ .Chart.Version }}"
          {{- if .Values.nodescaleadjuster.additionalArgs }}
            {{- toYaml .Values.nodescaleadjuster.additionalArgs | nindent 12 }}
          {{- end }}
          {{- if .Values.nodescaleadjuster.resources }}
          resources:
            {{- toYaml .Values.nodescaleadjuster.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.global.securityContext }}
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          {{- end }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.global.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.global.affinity }}
      affinity:
        {{- toYaml .Values.global.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.global.tolerations }}
      tolerations:
        {{- toYaml .Values.global.tolerations | nindent 8 }}
      {{- end }}
{{- end }}