# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: podgroup-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podgroup-controller
  template:
    metadata:
      labels:
        app: podgroup-controller
    spec:
      serviceAccountName: podgroup-controller
      containers:
        - name: podgroup-controller
          image: "{{ .Values.global.registry }}/{{ .Values.podgroupcontroller.image.name }}:{{ .Chart.Version }}"
          imagePullPolicy: {{ .Values.podgroupcontroller.image.pullPolicy }}
          {{- if .Values.podgroupcontroller.additionalArgs }}
          args:
            {{- toYaml .Values.podgroupcontroller.additionalArgs | nindent 12 }}
          {{- end }}
          {{- if .Values.podgroupcontroller.resources }}
          resources:
            {{- toYaml .Values.podgroupcontroller.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.global.securityContext }}
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          {{- end }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.global.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.global.affinity }}
      affinity:
        {{- toYaml .Values.global.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.global.tolerations }}
      tolerations:
        {{- toYaml .Values.global.tolerations | nindent 8 }}
      {{- end }}