{{- if .Values.postCleanup.enabled }}
# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.postCleanup.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: kai-operator
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
{{- end }}
