# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: batch/v1
kind: Job
metadata:
  name: pre-install-hook
  labels:
    app: pre-install-hook
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: webhookmanager
      restartPolicy: Never
      containers:
        - name: pre-install-hook
          image: "{{ .Values.global.registry }}/{{ .Values.webhookmanager.image.name }}:{{ .Chart.Version }}"
          imagePullPolicy: {{ .Values.webhookmanager.image.pullPolicy }}
          {{- if .Values.webhookmanager.resources }}
          resources:
            {{- toYaml .Values.webhookmanager.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.global.securityContext }}
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          {{- end }}
          args:
            - --namespace={{ .Release.Namespace }}
            - --service-name=binder
            - --upsert-secret
            - --secret-name={{ .Values.binder.certSecretName }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}