# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: queuecontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queuecontroller
  template:
    metadata:
      labels:
        app: queuecontroller
    spec:
      serviceAccountName: queuecontroller
      containers:
        - name: queuecontroller
          image: "{{ .Values.global.registry }}/{{ .Values.queuecontroller.image.name }}:{{ .Chart.Version }}"
          imagePullPolicy: {{ .Values.queuecontroller.image.pullPolicy }}
          ports:
            - containerPort: 9443
              name: webhook
          volumeMounts:
            - name: certs
              readOnly: true
              mountPath: "/tmp/k8s-webhook-server/serving-certs"
          {{- if .Values.queuecontroller.additionalArgs }}
          args:
            {{- toYaml .Values.queuecontroller.additionalArgs | nindent 12 }}
          {{- end }}
          {{- if .Values.queuecontroller.resources }}
          resources:
            {{- toYaml .Values.queuecontroller.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.global.securityContext }}
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          {{- end }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      volumes:
        - name: certs
          secret:
            secretName: {{ .Values.queuecontroller.certSecretName }}
            defaultMode: 420
      {{- if .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.global.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.global.affinity }}
      affinity:
        {{- toYaml .Values.global.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.global.tolerations }}
      tolerations:
        {{- toYaml .Values.global.tolerations | nindent 8 }}
      {{- end }} 
