# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: queuecontroller
  labels:
    app: queuecontroller
spec:
  ports:
  - port: 443
    targetPort: 9443
    protocol: TCP
    name: webhook
  selector:
    app: queuecontroller 