# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.global.clusterAutoscaling }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scaling-pod
  namespace: kai-scale-adjust
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
{{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
{{- end }}
{{- end }}