# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

name: KAI Scheduler - Pull Request
on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  validate-and-test:
    name: Validate & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Run validation
        run: make validate

      - name: Run tests
        run: make test

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage/coverage.out

  code-coverage-report:
    name: Code Coverage Report
    runs-on: ubuntu-latest
    needs: validate-and-test
    outputs:
      report: ${{ steps.coverage_reporter.outputs.coverage_report }}
    steps:
      - uses: fgrosse/go-coverage-report@8c1d1a09864211d258937b1b1a5b849f7e4f2682
        id: coverage_reporter
        with:
          coverage-artifact-name: "code-coverage"
          coverage-file-name: "coverage.out"
          root-package: "github.com/NVIDIA/KAI-scheduler"
          github-baseline-workflow-ref: update-coverage-badge.yaml
          skip-comment: true

  upload-report:
    name: Upload Coverage Report For Commenting
    runs-on: ubuntu-latest
    needs: code-coverage-report
    steps:
      - name: Save coverage report to file
        env:
          REPORT_BODY: ${{ needs.code-coverage-report.outputs.report }}
        run: echo "$REPORT_BODY" > coverage-report.txt
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-for-comment
          path: coverage-report.txt
      - name: Save PR number
        run: echo "${{ github.event.number }}" > pr_number.txt
      - name: Upload PR number
        uses: actions/upload-artifact@v4
        with:
          name: pr-number-for-comment
          path: pr_number.txt

  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      package_version: ${{ steps.package_version.outputs.PACKAGE_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract package version
        id: package_version
        run: |
          PACKAGE_VERSION=0.0.0-$(git rev-parse --short HEAD)
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
          echo $PACKAGE_VERSION

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create image cache directory
        run: mkdir images

      - name: Cache for docker images and helm chart
        uses: actions/cache@v4
        with:
          path: images
          key:  images-${{ github.sha }}

      - name: Build docker images
        run: |
          make build DOCKER_BUILDX_ADDITIONAL_ARGS=--load VERSION=$PACKAGE_VERSION
          docker save $(docker images --format '{{.Repository}}:{{.Tag}}' | grep $PACKAGE_VERSION) | gzip > images/docker_images.tgz

      - name: Build helm chart
        run: |
          helm package ./deployments/kai-scheduler -d ./charts --app-version $PACKAGE_VERSION --version $PACKAGE_VERSION
          cp charts/kai-scheduler-$PACKAGE_VERSION.tgz images/
