# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

name: Validate PR Title

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  validate-pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scopes: |
            scheduler
            binder
            podgrouper
            admission
            operator
            queue-controller
            pod-group-controller
            resource-reservation
            chart
            api
            node-scale-adjuster
            ci
            release
            docs
          requireScope: false
          ignoreLabels: |
            bot
            ignore-semantic-pull-request
